name: Download and process
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 21 */2 * *'

jobs:
  build_pages:
    name: Download METS files from Transkribus and convert them to TEIs
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
      TR_USER: ${{ secrets.TR_USER }}
      TR_PW: ${{ secrets.TR_PW}}
    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: manage folders
      run: ./scripts/manage_folders.sh
    - name: Install Saxon and Ant
      run: |
        apt-get update && apt-get install openjdk-11-jre-headless -y --no-install-recommend
        python -m pip config set global.break-system-packages true
        pip install -r requirements.txt
        wget https://sourceforge.net/projects/saxon/files/Saxon-HE/9.9/SaxonHE9-9-1-7J.zip/download && unzip -o download -d saxon && rm -rf download
    - name: prepare mets folder
      run: |
        mkdir -p ./data/mets
        rm -rf ./data/mets/*
    - name: Download METS Files
      run: |
        python ./scripts/fetch_mets.py
    - name: Transform to TEI
      run: |
        ./scripts/transform.sh
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Exported and Transformed B-VG-Transkribus Collections
    - name: Check for errors
      run: |
        if [ -f "$LOGPATH" ]; then exit 1; else exit 0; fi